### ISSUE TITLE
Entering a remote when asked causes a KeyError

### ISSUE THREAD

**Issue by danielsamuels** [onespacemedia/server-management#74]
On `pullmedia` with two hosts specified in server.json:

```bash
Available hosts: staging, production
Please enter a remote: [staging] production
Traceback (most recent call last):
  File "./manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/danielsamuels/Workspace/_client-projects/u/uk5g/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/danielsamuels/Workspace/_client-projects/u/uk5g/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/danielsamuels/Workspace/_client-projects/u/uk5g/.venv/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/danielsamuels/Workspace/_client-projects/u/uk5g/.venv/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/danielsamuels/Workspace/_client-projects/u/uk5g/.venv/lib/python3.6/site-packages/server_management/management/commands/pullmedia.py", line 13, in handle
    load_config(env, options.get('remote', ''), debug=options.get('debug', False))
  File "/Users/danielsamuels/Workspace/_client-projects/u/uk5g/.venv/lib/python3.6/site-packages/server_management/management/commands/_core.py", line 79, in load_config
    remote = config['remotes'][remote_prompt]
KeyError: True
```

The reason we're getting `True` as the `remote_prompt` value is because if you pass a `validate` method into `prompt()` - as we do [here](https://github.com/onespacemedia/server-management/blob/2a2fe5f13a12651b58735dbdb17387f44e72d040/server_management/management/commands/_core.py#L77) - [`prompt` will return the output of the `validate` callable](https://github.com/fabric/fabric/blob/294c08b3f96b728925dd8e77dd90e71810698156/fabric/operations.py#L219), which in this case is 'True' as we're using a lambda method.

**Comment by danielsamuels** [comment]
I was thinking about this this morning, I think we can simply change:

https://github.com/onespacemedia/server-management/blob/2a2fe5f13a12651b58735dbdb17387f44e72d040/server_management/management/commands/_core.py#L77

To be:

```python
 remote_prompt = prompt('Please enter a remote: ', default=remote_keys[0], validate=lambda x: remote_keys[x]) 
```

As if `x` doesn't exist in `remote_keys`, it'll raise a KeyError which will trigger [this](https://github.com/fabric/fabric/blob/294c08b3f96b728925dd8e77dd90e71810698156/fabric/operations.py#L218-L222) in the `validate()` method.

**Comment by lewiscollard** [comment]
I think you are right.
